In [5]:
import numpy as np



In [6]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
arr = np.array(lista)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
type(arr)

numpy.ndarray

In [12]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**TIPO DE DATOS NUMPY**

In [13]:
arruno = np.array([1,2,3,4])
print(arruno.dtype)
arruno

int64


array([1, 2, 3, 4])

In [14]:
arrdos = np.array([1,2,3,4], dtype ='float64')
print(arrdos.dtype)
arrdos

float64


array([1., 2., 3., 4.])

In [15]:
# convertir a tipo booleao
arruno = np.array([0,1,2,3,4,5,6,7,8,9], dtype ='bool')
print(arruno.dtype)
arruno

bool


array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [17]:
# convertir a tipo booleao
arruno = np.array([0,1,2,3,4,5,6,7,8,9,-1])
arruno = arruno.astype(np.bool_)
arruno

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [18]:
arruno = np.array([0,1,2,3,4,5,6,7,8,9])
arruno = arruno.astype(np.string_)
arruno

array([b'0', b'1', b'2', b'3', b'4', b'5', b'6', b'7', b'8', b'9'],
      dtype='|S21')

In [20]:
arruno = np.array(['0','1','2','3','4','5','6','7','8','9'])
arruno = arruno.astype(np.int8)
arruno

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int8)

**CONDICIONALES**

In [39]:
arruno = np.linspace(1,10,10, dtype='int')
arruno

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
# evaluacion que sea mayor que 3
indice_condicional = arruno > 3
indice_condicional

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [ ]:
# evaluacion que sea mayor que 3 y que sea menor 10

In [31]:
arruno[(indice_condicional) & (arruno < 7)]

array([4, 5, 6], dtype=int8)