In [ ]:
import numpy as np
# Mostrando la versió de numpy
print(np.__version__)

1.21.6


##CREANDO ARRAYS EN NUMPY

In [ ]:
''' NumPy se utiliza para trabajar con arrays. 
El objeto array en NumPy se llama ndarray.
Podemos crear un objeto NumPy ndarray utilizando la función array(). '''
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
'''type(): Esta función incorporada en Python nos dice el tipo del objeto que se le pasa. Como en el código anterior, muestra que arr es de tipo numpy.ndarray.

Para crear un ndarray, podemos pasar una lista, tupla o cualquier objeto tipo array al método array(), y se convertirá en un ndarray:'''

arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


###DIMENSIONES EN ARRAYS
Dimensiones en matrices
Una dimensión en los arrays es un nivel de profundidad del array (arrays anidados).

Matriz anidada: son matrices que tienen matrices como elementos.

###0 DIMENSIONES - ARRAYS

In [ ]:
'''
cREAR UNA DIMENSIÓN DE UN ARRAY
'''
arr = np.array(42)
print(arr)
arr.ndim

42


0

In [ ]:
''' Una matriz que tiene como elementos matrices 0-D se denomina matriz unidimensional o 1-D.

Estas son las matrices más comunes y básicas.'''

arr = np.array([1,2,3,4,5])
print(arr)
arr.ndim

[1 2 3 4 5]


1

In [ ]:
''' 
Matrices 2D
Un array que tiene como elementos arrays 1-D se denomina array 2-D. 
A menudo se utilizan para representar matrices o tensores de segundo orden.
NumPy tiene un sub-módulo dedicado a las operaciones matriciales llamado numpy.mat
'''
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
arr.ndim

[[1 2 3]
 [4 5 6]]


2

In [ ]:
'''
Matrices 3D
Una matriz que tiene matrices bidimensionales como elementos se denomina matriz 3D.

Suelen utilizarse para representar un tensor de 3er orden.
'''
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)
arr.ndim

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


3

In [ ]:
'''
Matrices de dimensiones superiores
Un array puede tener cualquier número de dimensiones.

Cuando se crea el array, se puede definir el número de dimensiones utilizando el argumento ndmin.
'''
#Ejemplo Crea un array con 5 dimensiones y comprueba que tiene 5 dimensiones:

arr = np.array([1,2,3,4,5], ndmin=5)
print(arr)
print('Número de dimensiones :', arr.ndim)

[[[[[1 2 3 4 5]]]]]
Número de dimensiones : 5


###Indexación de matrices en NumPy

In [ ]:
'''
Acceder a los elementos de una matriz
La indexación de matrices es lo mismo que acceder a un elemento de una matriz.

Puedes acceder a un elemento de la matriz haciendo referencia a su número de índice.

Los índices en los arrays de NumPy comienzan con 0, lo que significa que el primer elemento tiene índice 0, y el segundo tiene índice 1, etc.
'''
arr = np.array([1,2,3,4])
print(arr[0])
print(arr[1])
print(arr[2] + arr[3])


1
2
7


In [ ]:
'''
Acceso a matrices 3D
Para acceder a elementos de matrices tridimensionales podemos utilizar enteros separados por comas que representan las dimensiones y el índice del elemento.
'''
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [ ]:
'''
Indexación negativa
Utiliza la indexación negativa para acceder a un array desde el final.
'''
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Último elemento del 2º dim: ', arr[1, -1])

Último elemento del 2º dim:  10


###Segmentación de matrices NumPy

In [ ]:
'''
Rebanar en python significa tomar elementos de un índice dado a otro índice dado.
Pasamos slice en lugar de index así: [inicio:fin].
También podemos definir el paso, así: [inicio:fin:paso].
Si no pasamos start se considera 0
Si no pasamos end se considera la longitud del array en esa dimensión
Si no pasamos paso se considera 1
'''
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

#Nota: El resultado incluye el índice inicial, pero excluye el índice final.

[2 3 4 5]


In [ ]:
#Ejemplo Cortar elementos desde el índice 4 hasta el final de la matriz:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [ ]:
#Ejemplo Cortar elementos desde el principio hasta el índice 4 (no incluido):
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [ ]:
'''
Corte negativo
Utilice el operador menos para referirse a un índice a partir del final:

'''
# Ejemplo Corte desde el índice 3 del final hasta el índice 1 del final:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


##STEP

In [ ]:
'''
PASO
Utilice el valor de paso para determinar el paso del corte:
'''
# Example Return every other element from index 1 to index 5:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [ ]:
#Example Return every other element from the entire array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [ ]:
'''
Corte de matrices 2D
Ejemplo
A partir del segundo elemento, corte los elementos del índice 1 al índice 4 (no incluidos):
'''
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

#Nota: Recuerda que el segundo elemento tiene índice 1.

[7 8 9]


In [ ]:
# Example From both elements, return index 2:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [ ]:
# Ejemplo De ambos elementos, índice de corte 1 a índice 4 (no incluidos), esto devolverá un array 2D:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


##Tipos de datos en NumPy
Tipos de datos en Python
Por defecto Python tiene estos tipos de datos:

strings - usado para representar datos de texto, el texto se da entre comillas. e.g. "ABCD"
integer - utilizado para representar números enteros. e.g. -1, -2, -3
float - se utiliza para representar números reales. p. ej., 1,2, 42,42
boolean - se utiliza para representar Verdadero o Falso.
complex - se utiliza para representar números complejos. p. ej., 1,0 + 2,0j, 1,5 + 2,5j

###Tipos de Datos en NumPy
NumPy tiene algunos tipos de datos extra, y se refieren a tipos de datos con un caracter, como i para enteros, u para enteros sin signo, etc.

A continuación se muestra una lista de todos los tipos de datos en NumPy y los caracteres utilizados para representarlos.

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

###Comprobación del tipo de datos de una matriz
El objeto array de NumPy tiene una propiedad llamada dtype que devuelve el tipo de datos del array:

In [ ]:
# Ejemplo Obtener el tipo de datos de un objeto array:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [ ]:
#Ejemplo Obtener el tipo de datos de un array que contiene cadenas:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


###Creación de arrays con un tipo de datos definido
Utilizamos la función array() para crear matrices, esta función puede tomar un argumento opcional: dtype que nos permite definir el tipo de datos esperado de los elementos de la matriz:

In [ ]:
#Ejemplo Crear un array con tipo de datos string:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
''' Para i, u, f, S y U podemos definir también el tamaño. '''
# Ejemplo Crear un array con tipo de datos 4 bytes entero:

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


###¿Qué pasa si un valor no se puede convertir?
Si un tipo es dado en el cual los elementos no pueden ser convertidos entonces NumPy lanzará un ValueError.

ValueError: En Python ValueError se produce cuando el tipo de argumento pasado a una función es inesperado/incorrecto.

In [ ]:
#arr = np.array(['a', '2', '3'], dtype='i')

##Conversión del tipo de datos en matrices existentes
La mejor manera de cambiar el tipo de datos de un array existente, es hacer una copia del array con el método astype().

La función astype() crea una copia de la matriz y permite especificar el tipo de datos como parámetro.

El tipo de datos puede ser especificado usando una cadena, como 'f' para float, 'i' para integer etc. o puedes usar el tipo de datos directamente como float para float e int para integer.

In [ ]:
#Ejemplo Cambiar el tipo de datos de float a integer utilizando 'i' como valor del parámetro:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [ ]:
# Ejemplo Cambiar el tipo de datos de float a integer utilizando int como valor del parámetro:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [ ]:
# Ejemplo Cambiar el tipo de datos de entero a booleano:

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool
