**https://numpy.org/doc/**

In [1]:
import numpy as np

In [ ]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
arr = np.array(lista)

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**TIPOS DE DATOS NUMPY**

In [ ]:
 arruno = np.array([1,2,3,4])
 print(arruno.dtype)
 arruno

int64


array([1, 2, 3, 4])

In [ ]:
#convertir
arrdos = np.array([1,2,3,4], dtype='float64')
arrdos.dtype
arrdos

array([1., 2., 3., 4.])

In [ ]:
#convertir a tipo booleanos
arruno = np.array([0,1,2,3,4,5,6])
arruno = arruno.astype(np.bool_)
arruno

array([False,  True,  True,  True,  True,  True,  True])

In [ ]:
#convertir a tipo texto
arruno = np.array([0,1,2,3,4,5,6])
arruno = arruno.astype(np.string_)
arruno

array([b'0', b'1', b'2', b'3', b'4', b'5', b'6'], dtype='|S21')

In [ ]:
#convertir a tipo int
arruno = np.array(['0','1','2','3','4','5','6'])
arruno = arruno.astype(np.int8)
arruno

array([0, 1, 2, 3, 4, 5, 6], dtype=int8)

**ARRAY DE DIMENSIONES**

In [ ]:
import numpy as np

# mostrando la dimensión

scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [ ]:
# mostrando una dimensión

vector = np.array([1,2,3,4])
print(vector)
vector.ndim

[1 2 3 4]


1

In [ ]:
# mostrando 2 dimensión

matriz = np.array([[1,2,3,4],[5,6,7,8]])
print(matriz)
matriz.ndim

[[1 2 3 4]
 [5 6 7 8]]


2

In [ ]:
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],[[13, 13, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 13 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]


3

##AGREGAR O ELIMINAR DIMENSIONES

In [ ]:
#Agregando cantidades de dimensiones
vector10 = np.array([1,2,3,4], ndmin=10)
print(vector10)
vector10.ndim

[[[[[[[[[[1 2 3 4]]]]]]]]]]


10

In [ ]:
expand = np.expand_dims(np.array([1,2,3]), axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

##ELIMINAR DIMENSIONES

In [ ]:
# QUITAR LAS DIMENSIONES QUE NO SE ESTÉN UTILIZANDO

print(vector10,vector10.ndim)
vector_2 = np.squeeze(vector10)
print(vector_2, vector_2.ndim)


[[[[[[[[[[1 2 3 4]]]]]]]]]] 10
[1 2 3 4] 1


##CREANDO AARAYS


In [ ]:
import numpy as np

list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.rand()

0.7235145625845366

In [ ]:
np.random.rand(4)

array([0.56040077, 0.57107945, 0.3007318 , 0.70918482])

In [ ]:
np.random.rand(4,4)

array([[0.90285607, 0.21908724, 0.53687466, 0.79339989],
       [0.26348122, 0.61763704, 0.06366635, 0.3264995 ],
       [0.07474604, 0.62558271, 0.74074565, 0.28074687],
       [0.64326168, 0.34670696, 0.29501374, 0.82507296]])

In [ ]:
np.random.randint(1,15)

7

In [ ]:
np.random.randint(1,100,(10,10))

array([[11, 89, 95, 42, 68,  9, 45, 81, 93,  3],
       [ 1, 86, 39, 85, 97, 76, 50, 35, 38,  7],
       [60, 74,  4, 47, 85,  6, 68, 26, 98, 99],
       [38, 33, 44, 51,  1, 93,  8, 14, 27, 17],
       [63, 49, 18, 29, 43, 34, 96,  6, 22, 18],
       [50, 94, 54, 34, 11,  5, 58, 27, 74, 16],
       [43, 45, 54, 46, 25, 31, 62, 66, 11, 20],
       [23, 89, 70, 39, 50, 73, 83, 95, 28, 21],
       [94, 16, 29, 61, 59,  3, 37, 58, 11, 61],
       [34, 27, 10, 72, 19, 52, 73, 48, 86, 44]])

## SHAPE Y RESHAPE LA FORMA DE UN ARREGLO

In [ ]:
arr_3 = np.random.randint(1,10,(3,2))
arr_3


array([[2, 3],
       [9, 4],
       [6, 9]])

In [ ]:
arr_3.shape

(3, 2)

In [ ]:
arr_3

array([[2, 3],
       [9, 4],
       [6, 9]])

In [ ]:
arr_3.reshape(1,6)

array([[7, 3, 1, 2, 3, 3]])

In [ ]:
arr_3.reshape(2,3)

array([[8, 2, 3],
       [2, 1, 5]])

In [ ]:
np.reshape(arr_3,(1,6))

array([[8, 2, 3, 2, 1, 5]])

In [ ]:
#array original
arr_3

array([[8, 2],
       [3, 2],
       [1, 5]])

In [ ]:
np.reshape(arr_3,(2,3),'C')

array([[8, 2, 3],
       [2, 1, 5]])

In [ ]:
np.reshape(arr_3,(2,3),'F')

array([[8, 1, 2],
       [3, 2, 5]])

In [ ]:
np.reshape(arr_3,(2,3),'A')

array([[8, 2, 3],
       [2, 1, 5]])

##FUNCIONES PRINCIPALES EN NUMPY

In [ ]:
arr_4 = np.random.randint(1,20,10)

In [ ]:
matriz_4 = arr_4.reshape(2,5)
matriz_4

array([[13,  7, 17, 11, 18],
       [ 9, 10,  9,  3, 18]])

In [ ]:
arr_4.max()

18

In [ ]:
# 0 se refiere a columnas y 1 a filas
matriz_4.max(0)

array([13, 10, 17, 11, 18])

In [ ]:
arr_4.argmax()

4

In [ ]:
#Evalua en la matriz el valor mayor
matriz_4.argmax(0)

array([0, 1, 0, 0, 0])

In [ ]:
#Evalua en la matriz el valor menor en este caso son las columnas
matriz_4.argmin(0)

array([1, 0, 1, 1, 0])

In [ ]:
#Evaluando distancia de un pico a pico
arr_4
print(arr_4)
arr_4.ptp()


[13  7 17 11 18  9 10  9  3 18]


15

In [ ]:
#Evaluando distancia de un pico a pico
matriz_4.ptp(0)

array([4, 3, 8, 8, 0])

In [ ]:
#percentil
print(arr_4)
arr_4.sort()
print(arr_4)
np.percentile(arr_4,50)

[ 3  7  9  9 10 11 13 17 18 18]
[ 3  7  9  9 10 11 13 17 18 18]


10.5

In [ ]:
np.median(arr_4)

10.5

In [ ]:
np.median(matriz_4,0)

array([ 7. , 10. , 13. , 13.5, 14. ])

In [ ]:
#Desviación Standar
np.std(arr_4)

4.738143096192854

In [ ]:
#Varianza
np.var(arr_4)

22.45

In [ ]:
#media, es la suma de todos los valores del array dividido en la cantidad del array
np.mean(arr_4)

11.5

In [ ]:
a = np.array([[1,2],[3,4]])
print(a)
b = np.array([5,6])
print(b)

[[1 2]
 [3 4]]
[5 6]


In [ ]:
# Ahora vamos a concatenar 2 arrays
# sabemos que a y b son de dimensiones diferentes hay que acomodar a "b"

b = np.expand_dims(b,axis=0)
b.ndim

2

In [ ]:
# ahora ya se tiene las mismas dimensiones y procedemos a concatenar de manera de columnas
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#Ahora vamos a concatenar de manera de filas
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

##COPY

In [ ]:
import numpy as np

arr_5 = np.arange(0,11)
arr_5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
trozo_de_arr = arr_5[0:6]
trozo_de_arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
#implementar modificaciones en los arreglos
segundo_trozo_arr = arr_5.copy()
segundo_trozo_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#se va a menjar el arreglo sin dañar el arreglo original
segundo_trozo_arr[:] = 100
segundo_trozo_arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
arr_5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##CONDICIONALES

In [ ]:
arr_6 = np.linspace(1,10,10, dtype='int8')
arr_6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [ ]:
 indices_cond = arr_6 > 5
 indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
arr_6[(indices_cond) & (arr_6 < 9)]

array([6, 7, 8], dtype=int8)

In [ ]:
arr_6 [arr_6 > 5] = 99
arr_6[arr_6==99]


array([99, 99, 99, 99, 99], dtype=int8)

##OPERACIONES

In [ ]:
lista = [1,2]
lista

[1, 2]

In [ ]:
import numpy as np
arr_7 = np.arange(0,10)
arr_7_copy = arr_7.copy()
arr_7_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##OPERACIONES ARITMETICAS

In [ ]:
arr_7_copy * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr_7_copy + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
1/arr_7_copy

<ipython-input-7-3b2f1d71eeb8>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr_7_copy


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
matriz_7 = arr_7.reshape(2,5)
print(matriz_7)
matriz_7_copy = matriz_7.copy()
print(matriz_7_copy)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
matriz_7 + matriz_7_copy

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [ ]:
matriz_7 - matriz_7_copy

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
# Hacer producto punto
np.matmul(matriz_7,matriz_7_copy.T)

array([[ 30,  80],
       [ 80, 255]])

In [ ]:
# Hacer producto punto
matriz_7 @ matriz_7_copy.T

array([[ 30,  80],
       [ 80, 255]])