In [1]:
!python -V

Python 3.9.16


##CARGANDO DATOS

In [2]:
import numpy as np

In [4]:
km = np.loadtxt('/content/drive/MyDrive/Colab Notebooks/data/carros-km.txt', dtype=int)
km

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

In [5]:
anios = np.loadtxt('/content/drive/MyDrive/Colab Notebooks/data/carros-años.txt', dtype = int)
anios

array([2003, 1991, 1990, 2020, 2006, 2012, 2020, 2009, 2010, 2011, 2002,
       2007, 2001, 2020, 2009, 2016, 2012, 2020, 2016, 2017, 2002, 2020,
       1994, 1991, 2020, 2020, 2016, 2020, 2002, 1991, 1997, 1995, 2018,
       1991, 2014, 1995, 2020, 2020, 2009, 2020, 2013, 2003, 2020, 2002,
       2020, 2002, 2004, 2001, 2020, 2003, 2009, 2006, 2000, 2006, 2010,
       1994, 2007, 2020, 2020, 2020, 2020, 2020, 2017, 2011, 2001, 1996,
       2020, 1994, 2020, 2007, 1994, 2007, 1997, 2006, 2013, 1994, 2008,
       2008, 2020, 2020, 1999, 2007, 1993, 1995, 2020, 2020, 2016, 2011,
       2020, 2002, 2013, 2017, 2016, 2008, 2018, 2003, 2003, 2004, 2010,
       2020, 2006, 2001, 2020, 2015, 2018, 2017, 1992, 2001, 1993, 1995,
       2003, 2014, 2008, 2013, 2020, 2017, 2020, 2020, 2006, 2015, 2007,
       2005, 2017, 1998, 2020, 1999, 2020, 2009, 2003, 1994, 2020, 1994,
       2020, 2015, 1996, 1997, 1993, 2020, 1992, 1995, 2020, 1990, 2020,
       2020, 1991, 1990, 2012, 2007, 2013, 2000, 20

##OBTENER PROMEDIO DE KILOMETROS DE RECORRIDO

In [8]:
km_promedio = km / (2020 - anios)
km_promedio

<ipython-input-8-565736a96a06>:1: RuntimeWarning: invalid value encountered in true_divide
  km_promedio = km / (2020 - anios)


array([2.61235294e+03, 1.96965517e+02, 1.23743333e+03,            nan,
       1.83978571e+03, 1.34100000e+03,            nan, 7.05445455e+03,
       9.91970000e+03, 4.21977778e+03, 7.14388889e+02, 6.19384615e+02,
       4.72489474e+03,            nan, 3.76881818e+03, 2.89017500e+04,
       5.80612500e+03,            nan, 9.27150000e+03, 5.05766667e+03,
       5.62183333e+03,            nan, 3.77226923e+03, 3.55031034e+03,
                  nan,            nan, 1.44875000e+03,            nan,
       3.26933333e+03, 3.25451724e+03, 1.31143478e+03, 2.13328000e+03,
       8.86000000e+03, 1.16579310e+03, 1.51140000e+04, 1.75900000e+03,
                  nan,            nan, 5.02363636e+02,            nan,
       1.33450000e+04, 2.39776471e+03,            nan, 4.79455556e+03,
                  nan, 5.41944444e+02, 4.37156250e+03, 1.26052632e+02,
                  nan, 4.72641176e+03, 7.77763636e+03, 3.60685714e+03,
       3.38580000e+03, 6.71050000e+03, 3.53450000e+03, 3.11565385e+03,
      

In [9]:
type(km_promedio)

numpy.ndarray